server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: event-service
          uri: lb://EVENT-SERVICE
          predicates:
            - Path=/event-service/**
          filters:
            - RewritePath=/event-service/(?<segment>.*),/$\{segment}
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/review-service/**
          filters:
              - RewritePath=/review-service/(?<segment>.*),/$\{segment}
        - id: point-service
          uri: lb://POINT-SERVICE
          predicates:
            - Path=/point-service/**
          filters:
            - RewritePath=/point-service/(?<segment>.*),/$\{segment}